Use path prefix as default prefix when loading models
RelationalAI/rai-cli pull request #28
Opened 2022-08-04 16:19 UTC by NRHelmi

This PR adds the ability to the `cli` to use models paths as prefix by default like explained below:
* Default behavior
```
rai load-models DB_NAME --engine ENGINE_NAME path1/to/model1.rel path2/to/model2.rel
```
Models will be loaded under `path1/to/model1` and `path2/to/model2` prefixes.
* Override default behavior by specifying `--prefix`
```
rai load-models DB_NAME --engine ENGINE_NAME path1/to/model1.rel path2/to/model2.rel --prefix ""
```
Models will loaded under `model1` and `model2`

2022-08-04 16:45 UTC, larf311 commented
Need to update the CHANGELOG since this is a breaking change.

2022-10-05 15:10 UTC, bradlo commented
did this get merged? i dont see the branch in the list of remote branches?

2022-10-05 15:28 UTC, NRHelmi commented
> did this get merged? i dont see the branch in the list of remote branches?

@bradlo this work is not yet merged, the branch is still there
https://github.com/RelationalAI/rai-cli/tree/hnr-hierarchical-structure-models

2022-10-11 16:33 UTC, bradlo requested changes

2022-10-11 16:33 UTC, bradlo commented on CHANGELOG.md
> +* Use models path as a default prefix (could be overwitten by --prefix flag)
what *exactly* is the semantic for use of paths in file names? aside from the prefix arg? eg: i assume we canonicalize paths in some way? what does ../foo/../bar/baz/model.rel do? what if its a path from home, eg: ~/bar/baz/model? and what about a fully qualified path? the original idea was to use the basename, and prepend any prefix provided by the prefix arg. simple and unambiguous. what use case does this not handle?

2026-03-17 13:25 UTC, closed without merging